FLAGS = -Wall -fopenmp

all: pratica1 pratica2 pratica3

pratica1:
	$(CC) $(FLAGS) pratica1.c -o pratica1

pratica2:
	$(CC) $(FLAGS) pratica2.c -o pratica2

pratica3:
	$(CC) $(FLAGS) pratica3.c -o pratica3
