FLAGS = -Wall -fopenmp
bin = pratica1 pratica2 pratica3 pratica4

all: $(bin)

pratica1:
	$(CC) $(FLAGS) pratica1.c -o pratica1

pratica2:
	$(CC) $(FLAGS) pratica2.c -o pratica2

pratica3:
	$(CC) $(FLAGS) pratica3.c -o pratica3

pratica4:
	$(CC) $(FLAGS) pratica4.c -o pratica4

clean:
	rm $(bin)

.PHONY: all $(bin)
